"""add sended cullumn for telegram bot

Revision ID: 285dc64949f2
Revises: 891b92b56514
Create Date: 2021-08-03 23:47:08.957433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285dc64949f2'
down_revision = '891b92b56514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('sended', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'sended')
    # ### end Alembic commands ###
